# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-01 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20170731_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedcell',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
