# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20170801_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedrow',
            name='error_message',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedrow',
            name='has_error',
            field=models.BooleanField(default=False),
        ),
    ]
