# Generated by Django 2.0.3 on 2018-12-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_auto_20180123_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedcell',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='uploadedrow',
            name='error_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
