# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-23 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delegate', '0002_queuedorders_crm_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QueuedOrders',
            new_name='QueuedOrder',
        ),
    ]
