# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-23 19:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delegate', '0003_auto_20171023_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuedorder',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='queuedorder',
            name='sales_credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reg_sales_credit', to=settings.AUTH_USER_MODEL),
        ),
    ]
