F1_SPLIT = {'': ('NA', 'NA'),
            'aboriginal': ('Aboriginal', 'NA'),
            'aboriginal/gov': ('Aboriginal', 'Gov'),
            'aboriginal/industry': ('Aboriginal', 'Industry'),
            'aboriginal/industry/gov': ('Aboriginal', 'Industry'),
            'aboriginal/recruiting': ('Aboriginal', 'HR'),
            'aborignal': ('Aboriginal', 'NA'),
            'fin': ('FIN', 'NA'),
            'fin/aboriginal': ('FIN', 'Aboriginal'),
            'fin/gov': ('FIN', 'GOV'),
            'fin/gov/industry': ('FIN', 'GOV'),
            'fin/hr': ('FIN', 'HR'),
            'fin/industry': ('FIN', 'Industry'),
            'fin/recruiting': ('FIN', 'HR'),
            'fin/usa': ('FIN', 'USA'),
            'fin/usa/industry': ('FIN', 'Industry'),
            'gov': ('Gov', 'NA'),
            'gov/aboriginal': ('Gov', 'Aboriginal'),
            'gov/aboriginal/industry': ('Gov', 'Aboriginal'),
            'gov/fin': ('Gov', 'Fin'),
            'gov/fin/industry': ('Gov', 'Fin'),
            'gov/hr': ('Gov', 'HR'),
            'gov/hr/industry': ('Gov', 'HR'),
            'gov/hr/recruiting': ('Gov', 'HR'),
            'gov/industry': ('Gov', 'Industry'),
            'gov/industry/aboriginal': ('Gov', 'Industry'),
            'gov/industry/hr': ('Gov', 'Industry'),
            'gov/r': ('Gov', 'HR'),
            'gov/recruiting': ('Gov', 'HR'),
            'hr': ('HR', 'NA'),
            'hr/aboriginal': ('HR', 'Aboriginal'),
            'hr/fin': ('HR', 'FIN'),
            'hr/gov': ('HR', 'Gov'),
            'hr/gov/industry': ('HR', 'Gov'),
            'hr/gov/recruiting': ('HR', 'Gov'),
            'hr/industry': ('HR', 'Industry'),
            'hr/industry/gov': ('HR', 'Industry', 'Gov'),
            'hr/recruiting': ('HR', 'NA'),
            'hr/usa': ('HR', 'USA'),
            'indusrty': ('Industry', 'NA'),
            'industry': ('Industry', 'NA'),
            'industry/': ('Industry', 'NA'),
            'industry/aboriginal': ('Industry', 'Aboriginal'),
            'industry/aboriginal/gov': ('Industry', 'Aboriginal'),
            'industry/aborignial': ('Industry', 'Aboriginal'),
            'industry/fin': ('Industry', 'FIN'),
            'industry/go': ('Industry', 'Gov'),
            'industry/gov': ('Industry', 'Gov'),
            'industry/gov/aboriginal': ('Industry', 'Gov'),
            'industry/gov/fin': ('Industry', 'Gov'),
            'industry/gov/hr': ('Industry', 'Gov'),
            'industry/hr': ('Industry', 'HR'),
            'industry/hr/gov': ('Industry', 'HR'),
            'industry/recruiting': ('Industry', 'HR'),
            'internet': ('Industry', 'NA'),
            'recruiting': ('HR', 'NA'),
            'recruiting/hr': ('HR', 'NA'),
            'recruiting/gov': ('HR', 'Gov'),
            'recruitment': ('HR', 'NA'),
            'recuriting': ('HR', 'NA'),
            'reruiting': ('HR', 'NA'),
            'uk': ('NA', 'NA'),
            'usa': ('USA', 'NA'),
            'usa/aboriginal': ('USA', 'Aboriginal'),
            'usa/fin': ('USA', 'Fin'),
            'usa/gov': ('USA', 'Gov'),
            'usa/hr': ('USA', 'HR'),
            'usa/industry': ('USA', 'Industry'),
            'usa/industry/fin': ('Industry', 'Fin'),
            'yyy': ('NA', 'NA'),
            }

SPLIT_OPTIONS = ['1', '2', '3', '4', '5', '6', 'A1', 'A2', 'A3', 'Aboriginal',
                 'FED 1', 'FED 2', 'FED 3', 'FED 4', 'USA']

GEO_DICT = {'ab': 'West',
            'atlanta': 'USA',
            'africa': 'Other',
            'alberta': 'West',
            'australia': 'Other',
            'bahamas': 'Other',
            'barbados': 'Other',
            'bermuda': 'Other',
            'boston': 'USA',
            'china': 'Other',
            'eaf4/fed 4st': 'East',
            'east': 'East',
            'east/london': 'East',
            'east/maritimes': 'Maritimes/East',
            'east/west': 'East',
            'england': 'Other',
            'etobicoke': 'East',
            'europe': 'Other',
            'france': 'Other',
            'maritimes/east': 'Maritimes/East',
            'mexico': 'Other',
            'mississauga': 'East',
            'montreal': 'East',
            'new york': 'USA',
            'new zealand': 'Other',
            'nigeria': 'Other',
            'north': 'West',
            'north york': 'East',
            'north/west': 'West',
            'on': 'East',
            'qc': 'East',
            'toronto': 'East',
            'uk': 'Other',
            'usa': 'USA',
            'usa/east': 'USA',
            'west': 'West',
            'west/east': 'West',
            'hr': 'East',
            }
