# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-26 18:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0005_auto_20160729_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(blank=True, max_length=15)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('address_personal', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('name_for_badges', models.CharField(blank=True, max_length=30)),
                ('address1', models.CharField(blank=True, max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state_prov', models.CharField(blank=True, max_length=25)),
                ('postal_code', models.CharField(blank=True, max_length=15)),
                ('country', models.CharField(blank=True, max_length=25)),
                ('gst_hst_exempt', models.BooleanField(default=False)),
                ('qst_exempt', models.BooleanField(default=False)),
                ('gst_hst_exemption_number', models.CharField(max_length=25)),
                ('qst_exemption_number', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='RegDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField(unique=True)),
                ('priority_code', models.CharField(max_length=25)),
                ('sales_credit', models.CharField(max_length=50)),
                ('pre_tax_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_rate', models.DecimalField(decimal_places=5, max_digits=6)),
                ('hst_rate', models.DecimalField(decimal_places=5, max_digits=6)),
                ('qst_rate', models.DecimalField(decimal_places=5, max_digits=6)),
                ('pst_rate', models.DecimalField(decimal_places=5, max_digits=6)),
                ('payment_date', models.DateField(blank=True)),
                ('payment_method', models.CharField(blank=True, choices=[('V', 'Visa'), ('M', 'MasterCard'), ('A', 'AMEX'), ('C', 'Cheque'), ('W', 'Wire Transfer'), ('N', 'Credit Note'), ('O', 'Other method')], default=False, max_length=1)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_date', models.DateField(blank=True)),
                ('depost_method', models.CharField(blank=True, choices=[('V', 'Visa'), ('M', 'MasterCard'), ('A', 'AMEX'), ('C', 'Cheque'), ('W', 'Wire Transfer'), ('N', 'Credit Note'), ('O', 'Other method')], default=False, max_length=1)),
                ('fx_conversion_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('register_date', models.DateField(default=datetime.date.today)),
                ('cancellation_date', models.DateField(blank=True)),
                ('registration_status', models.CharField(choices=[('DP', 'Paid Delegate'), ('DU', 'Unpaid Delegate'), ('K', 'Speaker'), ('SP', 'Sponsor Paid'), ('SU', 'Sponsor Unpaid'), ('SD', 'Sponsor Deposit Paid'), ('G', 'Guest'), ('C', 'Comp (free with paids)'), ('DX', 'Delegate cancelled'), ('SX', 'Sponsor cancelled'), ('KX', 'Speaker cancelled')], default='DU', max_length=2)),
                ('invoice_notes', models.TextField(blank=True)),
                ('registration_notes', models.TextField(blank=True)),
                ('sponsorship_description', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Event')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reg_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reg_modifed_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registrants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(blank=True, max_length=15)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('email1', models.EmailField(blank=True, max_length=254)),
                ('email2', models.EmailField(blank=True, max_length=254)),
                ('phone1', models.CharField(blank=True, max_length=25)),
                ('phone2', models.CharField(blank=True, max_length=25)),
                ('contact_option', models.CharField(choices=[('D', 'Attention: delegate'), ('A', 'Attention: assistant'), ('C', 'cc to Assistant')], default='D', max_length=1)),
                ('delegate_notes', models.TextField(blank=True)),
                ('speaker_bio', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('assistant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Assistant')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='del_created_by', to=settings.AUTH_USER_MODEL)),
                ('crm_contact', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Contact')),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='del_modifed_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='regdetails',
            name='registrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Registrants'),
        ),
    ]
