# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_registrants_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='address_personal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='salutation',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='address1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='gst_hst_exemption_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_for_badges',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='qst_exemption_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='state_prov',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='regdetails',
            name='cancellation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regdetails',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='regdetails',
            name='deposit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regdetails',
            name='depost_method',
            field=models.CharField(blank=True, choices=[('V', 'Visa'), ('M', 'MasterCard'), ('A', 'AMEX'), ('C', 'Cheque'), ('W', 'Wire Transfer'), ('N', 'Credit Note'), ('O', 'Other method')], default=False, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='regdetails',
            name='fx_conversion_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='regdetails',
            name='invoice_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regdetails',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regdetails',
            name='registration_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regdetails',
            name='sponsorship_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrants',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Assistant'),
        ),
        migrations.AlterField(
            model_name='registrants',
            name='crm_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Contact'),
        ),
        migrations.AlterField(
            model_name='registrants',
            name='delegate_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrants',
            name='email1',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='registrants',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='registrants',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrants',
            name='phone1',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='registrants',
            name='phone2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='registrants',
            name='salutation',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='registrants',
            name='speaker_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrants',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
