# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20161104_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regdetails',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('V', 'Visa'), ('M', 'MasterCard'), ('A', 'AMEX'), ('C', 'Cheque'), ('W', 'Wire Transfer'), ('N', 'Credit Note'), ('O', 'Other method')], default=False, max_length=1, null=True),
        ),
    ]
