# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 00:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0006_auto_20161119_1941'),
        ('registration', '0005_auto_20161104_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_prov', models.CharField(max_length=25)),
                ('company_brand', models.CharField(choices=[('IC', 'Infonex Inc'), ('IT', 'INX-Training'), ('IU', 'Infonex (USA) Inc.')], default='IC', max_length=2)),
                ('gst_charged', models.BooleanField(default=False)),
                ('gst_rate', models.FloatField(default=0.05)),
                ('hst_charged', models.BooleanField(default=True)),
                ('hst_rate', models.FloatField(default=0.13)),
                ('qst_charged', models.BooleanField(default=False)),
                ('qst_rate', models.FloatField(default=0.09975)),
                ('pst_charged', models.BooleanField(default=False)),
                ('pst_rate', models.FloatField(default=0.0)),
                ('billing_currency', models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD')], default='CAD', max_length=3)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='details_created_by', to=settings.AUTH_USER_MODEL)),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state_prov', models.CharField(max_length=25)),
                ('postal_code', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=25)),
                ('hotel_url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='regdetails',
            name='registration_status',
            field=models.CharField(choices=[('DP', 'Delegate Paid'), ('DU', 'Delegate Unpaid'), ('DF', 'Delegate Free'), ('K', 'Speaker'), ('SP', 'Sponsor Paid'), ('SU', 'Sponsor Unpaid'), ('SD', 'Sponsor Deposit Paid'), ('G', 'Guest'), ('DX', 'Delegate cancelled'), ('SX', 'Sponsor cancelled'), ('KX', 'Speaker cancelled')], default='DU', max_length=2),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Venue'),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='details_modifed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='registrar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrar', to=settings.AUTH_USER_MODEL),
        ),
    ]
