# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20161119_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.Event'),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Venue'),
        ),
    ]
