# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20161122_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdetails',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='eventdetails',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='eventdetails',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventdetails',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='eventdetails',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='eventdetails',
            name='registrar',
        ),
        migrations.DeleteModel(
            name='EventDetails',
        ),
    ]
