# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20161122_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoptions',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
