# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20161203_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegEventOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.EventOptions')),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.RegDetails')),
            ],
        ),
    ]
