# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_regeventoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regdetails',
            name='sales_credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_credit', to=settings.AUTH_USER_MODEL),
        ),
    ]
