# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 17:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0013_auto_20170102_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regdetails',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='regdetails',
            name='deposit_date',
        ),
        migrations.RemoveField(
            model_name='regdetails',
            name='deposit_method',
        ),
        migrations.RemoveField(
            model_name='regdetails',
            name='fx_conversion_rate',
        ),
        migrations.RemoveField(
            model_name='regdetails',
            name='gst_rate',
        ),
        migrations.RemoveField(
            model_name='regdetails',
            name='hst_rate',
        ),
        migrations.RemoveField(
            model_name='regdetails',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='regdetails',
            name='invoice_notes',
        ),
        migrations.RemoveField(
            model_name='regdetails',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='regdetails',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='regdetails',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='regdetails',
            name='pre_tax_price',
        ),
        migrations.RemoveField(
            model_name='regdetails',
            name='priority_code',
        ),
        migrations.RemoveField(
            model_name='regdetails',
            name='pst_rate',
        ),
        migrations.RemoveField(
            model_name='regdetails',
            name='qst_rate',
        ),
        migrations.RemoveField(
            model_name='regdetails',
            name='sales_credit',
        ),
        migrations.RemoveField(
            model_name='regdetails',
            name='sponsorship_description',
        ),
        migrations.AddField(
            model_name='invoice',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deposit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deposit_method',
            field=models.CharField(blank=True, choices=[('V', 'Visa'), ('M', 'MasterCard'), ('A', 'AMEX'), ('C', 'Cheque'), ('W', 'Wire Transfer'), ('N', 'Credit Note'), ('O', 'Other method')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fx_conversion_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gst_rate',
            field=models.DecimalField(decimal_places=5, default=0.05, max_digits=6),
        ),
        migrations.AddField(
            model_name='invoice',
            name='hst_rate',
            field=models.DecimalField(decimal_places=5, default=0.13, max_digits=6),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('V', 'Visa'), ('M', 'MasterCard'), ('A', 'AMEX'), ('C', 'Cheque'), ('W', 'Wire Transfer'), ('N', 'Credit Note'), ('O', 'Other method')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pre_tax_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='priority_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pst_rate',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='invoice',
            name='qst_rate',
            field=models.DecimalField(decimal_places=5, default=0.09975, max_digits=6),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reg_details',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.RegDetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales_credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_credit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sponsorship_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
