# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_auto_20170206_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regdetails',
            name='registration_status',
            field=models.CharField(choices=[('', '-----------'), ('DP', 'Delegate Paid'), ('DU', 'Delegate Unpaid'), ('DF', 'Delegate Free'), ('K', 'Speaker'), ('SP', 'Sponsor Paid'), ('SU', 'Sponsor Unpaid'), ('SD', 'Sponsor Delegate'), ('SE', 'Sponsor Exhibitor'), ('G', 'Guest'), ('DX', 'Delegate cancelled'), ('SX', 'Sponsor cancelled'), ('KX', 'Speaker cancelled')], default='DU', max_length=2),
        ),
    ]
