# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_auto_20170210_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='priority_code',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='gst_rate',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.05, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='hst_rate',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.13, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='qst_rate',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.09975, max_digits=6, null=True),
        ),
    ]
