# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_auto_20170214_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='revised_flag',
            field=models.BooleanField(default=False),
        ),
    ]
