# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 18:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_invoice_revised_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='sales_credit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales_credit', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
