# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_auto_20170219_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regdetails',
            name='register_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='regdetails',
            name='registration_status',
            field=models.CharField(choices=[('', '-----------'), ('DU', 'Delegate Unpaid'), ('DP', 'Delegate Paid'), ('DF', 'Delegate Free'), ('K', 'Speaker'), ('SP', 'Sponsor Paid'), ('SU', 'Sponsor Unpaid'), ('SD', 'Sponsor Delegate'), ('SE', 'Sponsor Exhibitor'), ('G', 'Guest'), ('DX', 'Delegate cancelled'), ('SX', 'Sponsor cancelled'), ('KX', 'Speaker cancelled')], default='DU', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='regeventoptions',
            unique_together=set([('reg', 'option')]),
        ),
    ]
