# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_auto_20170504_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regdetails',
            name='registration_status',
            field=models.CharField(choices=[('', '-----------'), ('DU', 'Delegate Unpaid'), ('DP', 'Delegate Paid'), ('DF', 'Delegate Free'), ('K', 'Speaker'), ('SP', 'Sponsor Paid'), ('SU', 'Sponsor Unpaid'), ('SD', 'Sponsor Delegate'), ('SE', 'Sponsor Exhibitor'), ('G', 'Guest'), ('DX', 'Delegate cancelled - paid'), ('UX', 'Delegate cancelled - unpaid'), ('SX', 'Sponsor cancelled'), ('KX', 'Speaker cancelled'), ('B', 'Substituted Out')], default='DU', max_length=2),
        ),
    ]
