# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-24 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_auto_20170518_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regdetails',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='reg_modifed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registrants',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Assistant'),
        ),
        migrations.AlterField(
            model_name='registrants',
            name='crm_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Person'),
        ),
    ]
