# Generated by Django 2.0 on 2018-01-23 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_auto_20170824_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sales_credit',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sales_credit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='regdetails',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='reg_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registrants',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='del_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registrants',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='del_modifed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registrants',
            name='phone1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='registrants',
            name='phone2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
