# Generated by Django 2.0.3 on 2018-12-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_auto_20181220_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='address_personal',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='salutation',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='gst_rate',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.05, max_digits=6),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='hst_rate',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.13, max_digits=6),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pre_tax_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='qst_rate',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.09975, max_digits=6),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sponsorship_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regdetails',
            name='registration_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='registrants',
            name='delegate_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='registrants',
            name='email1',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='registrants',
            name='email2',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='registrants',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='registrants',
            name='phone1',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='registrants',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='registrants',
            name='salutation',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='registrants',
            name='speaker_bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='registrants',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
