# Generated by Django 2.2.4 on 2019-08-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_auto_20181221_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoptions',
            name='primary',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
