# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='geo',
            field=models.CharField(choices=[('East', 'East'), ('West', 'West'), ('Maritimes/East', 'Maritimes'), ('USA', 'USA'), ('Other', 'Other Foreign'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
    ]
