# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20160606_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DELEGATE', 'Paying Delegate'), ('SPEAKER', 'Speaker'), ('GUEST', 'Guest (non-revenue)'), ('SPONSOR', 'Sponsor Representative'), ('OTHER', 'Other attendee')], default='DELEGATE', max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Person')),
            ],
        ),
    ]
