# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20160729_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
