# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 20:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0008_auto_20161122_1505'),
        ('crm', '0006_auto_20161119_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='billing_currency',
            field=models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD')], default='CAD', max_length=3),
        ),
        migrations.AddField(
            model_name='event',
            name='company_brand',
            field=models.CharField(choices=[('IC', 'Infonex Inc'), ('IT', 'INX-Training'), ('IU', 'Infonex (USA) Inc.')], default='IC', max_length=2),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='details_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='date modified'),
        ),
        migrations.AddField(
            model_name='event',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='gst_charged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='gst_rate',
            field=models.FloatField(default=0.05),
        ),
        migrations.AddField(
            model_name='event',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Venue'),
        ),
        migrations.AddField(
            model_name='event',
            name='hst_charged',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='hst_rate',
            field=models.FloatField(default=0.13),
        ),
        migrations.AddField(
            model_name='event',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='details_modifed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='pst_charged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='pst_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='event',
            name='qst_charged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='qst_rate',
            field=models.FloatField(default=0.09975),
        ),
        migrations.AddField(
            model_name='event',
            name='registrar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registrar', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='state_prov',
            field=models.CharField(default='ON', max_length=25),
            preserve_default=False,
        ),
    ]
