# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20170107_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterListSelections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo', models.CharField(blank=True, choices=[('East', 'East'), ('West', 'West'), ('Maritimes/East', 'Maritimes'), ('USA', 'USA'), ('Other', 'Other Foreign'), ('Unknown', 'Unknown'), ('', '---')], default='', max_length=10)),
                ('main_category', models.CharField(blank=True, choices=[('HR', 'HR'), ('FIN', 'FIN'), ('Industry', 'Industry'), ('Aboriginal', 'Aboriginal'), ('Gov', 'Gov'), ('NA', 'None'), ('', '---')], default='', max_length=25)),
                ('main_category2', models.CharField(blank=True, choices=[('HR', 'HR'), ('FIN', 'FIN'), ('Industry', 'Industry'), ('Aboriginal', 'Aboriginal'), ('Gov', 'Gov'), ('NA', 'None'), ('', '---')], default='', max_length=15)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('dept', models.CharField(blank=True, max_length=255)),
                ('include_exclude', models.CharField(choices=[('include', 'include'), ('exclude', 'exclude')], default='include', max_length=7)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Event')),
            ],
        ),
    ]
