# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 17:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0013_auto_20170110_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventassignment',
            name='role',
            field=models.CharField(choices=[('SA', 'Sales'), ('SP', 'Sponsorship'), ('PD', 'Conference Developer'), ('NA', 'Unassigned')], default='SA', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='eventassignment',
            unique_together=set([('user', 'event')]),
        ),
    ]
