# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_auto_20170111_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='personallistselections',
            name='filter_master_selects',
            field=models.BooleanField(default=True),
        ),
    ]
