# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_personallistselections_filter_master_selects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personallistselections',
            name='filter_master_selects',
        ),
        migrations.AddField(
            model_name='eventassignment',
            name='filter_master_selects',
            field=models.BooleanField(default=True),
        ),
    ]
