# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_auto_20170124_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listselection',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='listselection',
            name='event',
        ),
        migrations.RemoveField(
            model_name='listselection',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personflag',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='personflag',
            name='event',
        ),
        migrations.RemoveField(
            model_name='personflag',
            name='person',
        ),
        migrations.RemoveField(
            model_name='reghistory',
            name='event',
        ),
        migrations.RemoveField(
            model_name='reghistory',
            name='person',
        ),
        migrations.DeleteModel(
            name='ListSelection',
        ),
        migrations.DeleteModel(
            name='PersonFlag',
        ),
        migrations.DeleteModel(
            name='RegHistory',
        ),
    ]
