# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_auto_20170130_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='personallistselections',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
