# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_personallistselections_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_web_site',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
