# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_event_event_web_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changes',
            name='dept',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
