# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_auto_20170227_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='method',
            field=models.CharField(choices=[('Pitch', 'Sales Pitch (Phone)'), ('EPitch', 'Sales Pitch (Email)'), ('Followup', 'Follow-up Call'), ('Email', 'Follow-up Email'), ('Marketing', 'Marketing Email'), ('Registration', 'Delegate registration'), ('Speaker', 'Speaker confirmation'), ('Sponsor', 'Sponsor booking'), ('Research', 'PD Research Call')], default='Pitch', max_length=20),
        ),
    ]
