# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_auto_20170517_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='default_cat1',
            field=models.CharField(choices=[('HR', 'HR'), ('FIN', 'FIN'), ('Industry', 'Industry'), ('Aboriginal', 'Aboriginal'), ('Gov', 'Gov'), ('USA', 'USA'), ('NA', 'None')], default='Industry', max_length=25),
        ),
        migrations.AddField(
            model_name='event',
            name='default_cat2',
            field=models.CharField(choices=[('HR', 'HR'), ('FIN', 'FIN'), ('Industry', 'Industry'), ('Aboriginal', 'Aboriginal'), ('Gov', 'Gov'), ('USA', 'USA'), ('NA', 'None')], default='NA', max_length=15),
        ),
        migrations.AddField(
            model_name='event',
            name='default_dept',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
