# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 15:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0025_auto_20170524_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='method',
            field=models.CharField(choices=[('Pitch', 'Sales Pitch (Phone)'), ('EPitch', 'Sales Pitch (Email)'), ('Followup', 'Follow-up Call'), ('Email', 'Follow-up Email'), ('NA', 'Not Available'), ('Marketing', 'Marketing Email'), ('Registration', 'Delegate registration'), ('Speaker', 'Speaker confirmation'), ('Sponsor', 'Sponsor booking'), ('Research', 'PD Research Call')], default='Pitch', max_length=20),
        ),
    ]
