# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_auto_20170530_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email_alternate',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_alternate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
