# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_auto_20170811_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
