# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_auto_20170901_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
