# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-19 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_auto_20170928_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='assistant_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='assistant_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
