# Generated by Django 2.0 on 2018-01-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_auto_20171019_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_alternate',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_main',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
