# Generated by Django 2.0 on 2018-01-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_auto_20180123_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changes',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='changes',
            name='phone_main',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
