# Generated by Django 2.0.3 on 2018-12-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_auto_20180123_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changes',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='changes',
            name='company',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='changes',
            name='dept',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='changes',
            name='division1',
            field=models.CharField(blank=True, choices=[('1', '1 - Misc'), ('2', '2 - Misc'), ('3', '3 - Misc'), ('4', '4 - Misc'), ('5', '5 - Misc'), ('6', '6 - Misc'), ('A1', '1 - Accounting'), ('A2', '2 - Accounting'), ('A3', '3 - Accounting'), ('Aboriginal', 'Aboriginal'), ('FED 1', 'FED 1'), ('FED 2', 'FED 2'), ('FED 3', 'FED 3'), ('FED 4', 'FED 4'), ('USA', 'USA'), ('NA', 'Not Determined')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='changes',
            name='division2',
            field=models.CharField(blank=True, choices=[('1', '1 - Misc'), ('2', '2 - Misc'), ('3', '3 - Misc'), ('4', '4 - Misc'), ('5', '5 - Misc'), ('6', '6 - Misc'), ('A1', '1 - Accounting'), ('A2', '2 - Accounting'), ('A3', '3 - Accounting'), ('Aboriginal', 'Aboriginal'), ('FED 1', 'FED 1'), ('FED 2', 'FED 2'), ('FED 3', 'FED 3'), ('FED 4', 'FED 4'), ('USA', 'USA'), ('NA', 'Not Determined')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='changes',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='changes',
            name='geo',
            field=models.CharField(blank=True, choices=[('East', 'East'), ('West', 'West'), ('Maritimes/East', 'Maritimes'), ('USA', 'USA'), ('Other', 'Other Foreign'), ('Unknown', 'Unknown')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='changes',
            name='industry',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='changes',
            name='main_category',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('FIN', 'FIN'), ('Industry', 'Industry'), ('Aboriginal', 'Aboriginal'), ('Gov', 'Gov'), ('USA', 'USA'), ('NA', 'None')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='changes',
            name='main_category2',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('FIN', 'FIN'), ('Industry', 'Industry'), ('Aboriginal', 'Aboriginal'), ('Gov', 'Gov'), ('USA', 'USA'), ('NA', 'None')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='changes',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='changes',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='changes',
            name='phone_main',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='changes',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='default_cat1',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('FIN', 'FIN'), ('Industry', 'Industry'), ('Aboriginal', 'Aboriginal'), ('Gov', 'Gov'), ('USA', 'USA'), ('NA', 'None')], default='Industry', max_length=25),
        ),
        migrations.AlterField(
            model_name='event',
            name='default_cat2',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('FIN', 'FIN'), ('Industry', 'Industry'), ('Aboriginal', 'Aboriginal'), ('Gov', 'Gov'), ('USA', 'USA'), ('NA', 'None')], default='NA', max_length=15),
        ),
        migrations.AlterField(
            model_name='event',
            name='default_dept',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_web_site',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='assistant_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='assistant_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='person',
            name='dept',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='division2',
            field=models.CharField(blank=True, choices=[('1', '1 - Misc'), ('2', '2 - Misc'), ('3', '3 - Misc'), ('4', '4 - Misc'), ('5', '5 - Misc'), ('6', '6 - Misc'), ('A1', '1 - Accounting'), ('A2', '2 - Accounting'), ('A3', '3 - Accounting'), ('Aboriginal', 'Aboriginal'), ('FED 1', 'FED 1'), ('FED 2', 'FED 2'), ('FED 3', 'FED 3'), ('FED 4', 'FED 4'), ('USA', 'USA'), ('NA', 'Not Determined')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='email_alternate',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='industry',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='linkedin',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_alternate',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_main',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='personallistselections',
            name='company',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='personallistselections',
            name='dept',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='personallistselections',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='personallistselections',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
