# Generated by Django 3.0.3 on 2020-02-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_event_room_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlistselections',
            name='geo',
            field=models.CharField(blank=True, choices=[('East', 'East'), ('West', 'West'), ('Maritimes/East', 'Maritimes'), ('USA', 'USA'), ('Other', 'Other Foreign'), ('Unknown', 'Unknown'), ('', '---')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='personallistselections',
            name='geo',
            field=models.CharField(blank=True, choices=[('East', 'East'), ('West', 'West'), ('Maritimes/East', 'Maritimes'), ('USA', 'USA'), ('Other', 'Other Foreign'), ('Unknown', 'Unknown'), ('', '---')], default='', max_length=20),
        ),
    ]
