# Generated by Django 3.0.8 on 2020-07-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_auto_20200730_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='date modified'),
        ),
    ]
